npm install async
npm install backbone
npm install colors
npm install commander
npm install cookies
npm install connect
npm install express
npm install express-partials
npm install ejs
npm install jade
npm install jake
npm install jshint
npm install less
npm install markdown
npm install marked
npm install mkdirp
npm install mongodb
npm install mongoose
npm install moment
npm install nconf
npm install nodemailer
npm install optimist
npm install oauth
npm install passport
npm install q
npm install redis
npm install request
npm install should
npm install socket.io
npm install stylus
npm install underscore


