npm install express
npm install request
npm install async
npm install socket.io
npm install underscore
npm install jade
npm install connect
npm install redis
npm install mongoose
npm install optimist
npm install commander
npm install stylus
npm install colors
npm install jshint
npm install mongodb
npm install less
npm install moment
npm install marked
npm install nodemailer
npm install backbone
npm install forever
npm install should
npm install q
npm install cookies
npm install nconf
npm install passport
npm install markdown
npm install jake
npm install mkdirp
npm install oauth

