npm install -g coffee-script
npm install -g cordova
npm install -g docco
npm install -g express
npm install -g grunt
npm install -g hexo
npm install -g html2jade
npm install -g jslint
npm install -g karma
npm install -g mocha
npm install -g nodemon
npm install -g uglify-js
